name: Run Tests

on:
  push:
    tags:
      - '*'
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  cancel_previous_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  run_tests:
    needs: cancel_previous_runs
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
        - {python: "3.7", tensorflow: "2.0"}
        - {python: "3.7", tensorflow: "2.1"}
        - {python: "3.8", tensorflow: "2.2"}
        - {python: "3.8", tensorflow: "2.3"}
        - {python: "3.8", tensorflow: "2.4"}
        - {python: "3.9", tensorflow: "2.5"}
        - {python: "3.9", tensorflow: "2.7"}
        - {python: "3.9", tensorflow: "2.8"}
        - {python: "3.9", tensorflow: "2.9"}
        - {python: "3.10", tensorflow: "2.10"}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up environment
      run: |
        echo "LINUX_VERSION=$(uname -rs)" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.config.python }}

    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{env.LINUX_VERSION}}-pip-${{ matrix.config.python }}-${{ hashFiles('setup.py') }}
        restore-keys: ${{env.LINUX_VERSION}}-pip-${{ matrix.config.python }}-

    - name: Install package & dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U wheel setuptools
        pip install -U .[test] tensorflow==${{ matrix.config.tensorflow }}
        python -c "import dca"

    - name: Run tests
      run: pytest -vv
